name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    environment: cloudpanel
    
    steps:
      - name: Install deployment dependencies
        run: |
          apk add --no-cache openssh-client git

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Deploy to server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SFTP_USERNAME }}
          pass: ${{ secrets.SFTP_PASSWORD }}
          connect_timeout: 10s
          first_ssh: |
            mkdir -p ${{ secrets.DEPLOY_PATH }}/dist
          scp: |
            './Code/api/dist/*' => ${{ secrets.DEPLOY_PATH }}/dist/
            './Code/api/package.json' => ${{ secrets.DEPLOY_PATH }}/
            './Code/api/yarn.lock' => ${{ secrets.DEPLOY_PATH }}/
          last_ssh: |
            cd ${{ secrets.DEPLOY_PATH }}
            yarn install --production --frozen-lockfile
            pm2 restart api.resumevita.com || pm2 start dist/index.js --name api.resumevita.com
            pm2 save
