name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    environment: cloudpanel
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
    
    steps:
      - name: Install deployment dependencies
        run: |
          apk add --no-cache openssh-client git

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "StrictHostKeyChecking no" > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Backup current deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            if [ -d "dist" ]; then
              timestamp=$(date +%Y%m%d_%H%M%S)
              mkdir -p backups
              cp -r dist "backups/dist_$timestamp"
              find backups -type d -name "dist_*" -mtime +5 -exec rm -rf {} \;
            fi

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "Code/api/dist/*,Code/api/package.json,Code/api/yarn.lock"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 2
          overwrite: true

      - name: Install dependencies and start PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            export PUPPETEER_SKIP_DOWNLOAD=true
            yarn install --production --frozen-lockfile
            pm2 stop api.resumevita.com || true
            pm2 start dist/index.js --name api.resumevita.com
            pm2 save
