name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudpanel
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
      DEPLOY_PATH: "/home/resumevita-api/htdocs/api.resumevita.com"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'Code/api/yarn.lock'

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Debug SSH Connection
        run: |
          echo "Testing SSH connection..."
          echo "Username: $SSH_USER"
          echo "Host: $SSH_HOST"
          echo "Deploy path: $DEPLOY_PATH"
          
          # Test basic SSH connection
          echo "Step 1: Testing basic SSH connection..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "pwd && ls -la ~/"
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: 3.7.54.65

      - name: Setup deploy directory
        run: |
          echo "Setting up deploy directory with correct permissions..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
            mkdir -p $DEPLOY_PATH && \
            chmod -R 755 $DEPLOY_PATH
          "
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: 3.7.54.65

      - name: Deploy with SSH
        if: success()
        run: |
          cd Code/api
          echo "Creating dist directory..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p $DEPLOY_PATH/dist"
          
          echo "Copying dist files..."
          sshpass -p "$SSH_PASS" scp -r dist/* $SSH_USER@$SSH_HOST:$DEPLOY_PATH/dist/
          
          echo "Copying package files..."
          sshpass -p "$SSH_PASS" scp package.json yarn.lock $SSH_USER@$SSH_HOST:$DEPLOY_PATH/
          
          echo "Installing dependencies and starting service..."
          sshpass -p "$SSH_PASS" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd $DEPLOY_PATH && \
            export PUPPETEER_SKIP_DOWNLOAD=true && \
            yarn install --production --frozen-lockfile && \
            pm2 stop api.resumevita.com || true && \
            pm2 start dist/index.js --name api.resumevita.com && \
            pm2 save"
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_PASS: ${{ secrets.SSH_PASSWORD }}
          SSH_HOST: 3.7.54.65
