name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudpanel
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'Code/api/yarn.lock'

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Debug Connection
        run: |
          echo "Testing connection..."
          echo "Username length: ${#SFTP_USER}"
          echo "Password length: ${#SFTP_PASS}"
          echo "Host: $SFTP_HOST"
          echo "Attempting simple SSH connection..."
          sshpass -p "$SFTP_PASS" ssh -v -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "echo 'Connection test'"
        env:
          SFTP_USER: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
          SFTP_HOST: ${{ secrets.SERVER_HOST }}

      - name: Deploy to server
        run: |
          cd Code/api
          echo "Creating dist directory..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "mkdir -p $DEPLOY_PATH/dist"
          
          echo "Copying dist files..."
          sshpass -p "$SFTP_PASS" scp -v -o StrictHostKeyChecking=no -r dist/* $SFTP_USER@$SFTP_HOST:$DEPLOY_PATH/dist/
          
          echo "Copying package files..."
          sshpass -p "$SFTP_PASS" scp -v -o StrictHostKeyChecking=no package.json yarn.lock $SFTP_USER@$SFTP_HOST:$DEPLOY_PATH/
          
          echo "Running deployment commands..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "cd $DEPLOY_PATH && \
            export PUPPETEER_SKIP_DOWNLOAD=true && \
            yarn install --production --frozen-lockfile && \
            pm2 stop api.resumevita.com || true && \
            pm2 start dist/index.js --name api.resumevita.com && \
            pm2 save"
        env:
          SFTP_USER: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
          SFTP_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
