name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudpanel
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'Code/api/yarn.lock'

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Debug Connection
        run: |
          echo "Testing connection..."
          echo "Username length: ${#SFTP_USER}"
          echo "Password length: ${#SFTP_PASS}"
          echo "Host: $SFTP_HOST"
          echo "Deploy path: $DEPLOY_PATH"
          
          # Test basic SSH connection
          echo "Step 1: Testing basic SSH connection..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "echo 'SSH connection successful'"
          
          # Check home directory
          echo "Step 2: Checking home directory..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "pwd"
          
          # Try to create a test file
          echo "Step 3: Testing file creation in home directory..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "touch test.txt && echo 'File created' || echo 'Failed to create file'"
          
          # Check if we can access deploy path
          echo "Step 4: Testing deploy path access..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "cd $DEPLOY_PATH 2>/dev/null && echo 'Deploy path accessible' || echo 'Cannot access deploy path'"
        env:
          SFTP_USER: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
          SFTP_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

      - name: Deploy to server
        if: success()
        run: |
          cd Code/api
          echo "Creating dist directory..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "mkdir -p $DEPLOY_PATH/dist" || echo "Failed to create directory"
          
          echo "Copying dist files..."
          sshpass -p "$SFTP_PASS" scp -r dist/* $SFTP_USER@$SFTP_HOST:$DEPLOY_PATH/dist/ || echo "Failed to copy dist"
          
          echo "Copying package files..."
          sshpass -p "$SFTP_PASS" scp package.json yarn.lock $SFTP_USER@$SFTP_HOST:$DEPLOY_PATH/ || echo "Failed to copy package files"
          
          echo "Running deployment commands..."
          sshpass -p "$SFTP_PASS" ssh -o StrictHostKeyChecking=no $SFTP_USER@$SFTP_HOST "cd $DEPLOY_PATH && \
            export PUPPETEER_SKIP_DOWNLOAD=true && \
            yarn install --production --frozen-lockfile && \
            pm2 stop api.resumevita.com || true && \
            pm2 start dist/index.js --name api.resumevita.com && \
            pm2 save"
        env:
          SFTP_USER: ${{ secrets.SFTP_USERNAME }}
          SFTP_PASS: ${{ secrets.SFTP_PASSWORD }}
          SFTP_HOST: ${{ secrets.SERVER_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
