name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudpanel
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'Code/api/yarn.lock'

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Deploy to CloudPanel via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SERVER_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './Code/api/dist/*'
          remote_path: ${{ secrets.DEPLOY_PATH }}/dist
          sftp_only: true
          
      - name: Deploy package files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SERVER_HOST }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: './Code/api/package.json,./Code/api/yarn.lock'
          remote_path: ${{ secrets.DEPLOY_PATH }}
          sftp_only: true

      - name: Install dependencies and restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            yarn install --production --frozen-lockfile
            pm2 restart api.resumevita.com || pm2 start dist/index.js --name api.resumevita.com
            pm2 save
