name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cloudpanel
    env:
      PUPPETEER_SKIP_DOWNLOAD: "true"
    
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'Code/api/yarn.lock'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v4.1.10
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_PASSWORD }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          TARGET: ${{ secrets.DEPLOY_PATH }}
          SOURCE: "Code/api/"
          ARGS: "-avzr --delete"
          SCRIPT_AFTER: |
            cd ${{ secrets.DEPLOY_PATH }}
            export PUPPETEER_SKIP_DOWNLOAD=true
            yarn install --production --frozen-lockfile
            pm2 stop api.resumevita.com || true
            pm2 start dist/index.js --name api.resumevita.com
            pm2 save
