name: Deploy API to AWS CloudPanel

on:
  push:
    branches:
      - main
    paths:
      - 'Code/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    environment: cloudpanel
    
    steps:
      - name: Install deployment dependencies
        run: |
          apk add --no-cache openssh-client git

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: Code/api
        run: yarn install --frozen-lockfile

      - name: Build application
        working-directory: Code/api
        run: yarn build

      - name: Deploy via SFTP
        uses: ssh-actions/ssh-sftp-action@main
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: '22'
          upload-from: |
            Code/api/dist
            Code/api/package.json
            Code/api/yarn.lock
          upload-to: ${{ secrets.DEPLOY_PATH }}
          ignore-files: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env*
            **/backups/**

      - name: Install dependencies and restart PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            yarn install --production --frozen-lockfile
            pm2 restart api.resumevita.com || pm2 start dist/index.js --name api.resumevita.com
            pm2 save
